// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtaqAR1PiinRSXEXP8-pr8wkYXlVShydE',
    appId: '1:906975937291:web:dbfe4577133065bdff580e',
    messagingSenderId: '906975937291',
    projectId: 'smart-cucumber-agriculture',
    authDomain: 'smart-cucumber-agriculture.firebaseapp.com',
    databaseURL: 'https://smart-cucumber-agriculture-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-cucumber-agriculture.firebasestorage.app',
    measurementId: 'G-90D6Y5S6KJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApRVJp3KmNMwd2KUoS4FHk-sqr7TmMoAU',
    appId: '1:906975937291:android:91efed5c2b5c9a8aff580e',
    messagingSenderId: '906975937291',
    projectId: 'smart-cucumber-agriculture',
    databaseURL: 'https://smart-cucumber-agriculture-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-cucumber-agriculture.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjW4H1vYTU5EfcdIRGUe10Tf_BD8zobRc',
    appId: '1:906975937291:ios:41ab03d90fab1964ff580e',
    messagingSenderId: '906975937291',
    projectId: 'smart-cucumber-agriculture',
    databaseURL: 'https://smart-cucumber-agriculture-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-cucumber-agriculture.firebasestorage.app',
    iosBundleId: 'com.example.smartCucumberAgricultureSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtaqAR1PiinRSXEXP8-pr8wkYXlVShydE',
    appId: '1:906975937291:web:430391c2ce328a5fff580e',
    messagingSenderId: '906975937291',
    projectId: 'smart-cucumber-agriculture',
    authDomain: 'smart-cucumber-agriculture.firebaseapp.com',
    databaseURL: 'https://smart-cucumber-agriculture-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-cucumber-agriculture.firebasestorage.app',
    measurementId: 'G-HJTBSV9D27',
  );
}
